name: Build Quarkus Native Image (Linux)

on:
  workflow_dispatch:
  push:
    branches:
      - example/paza-auto

jobs:
  native-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm-community
          java-version: 21
          components: native-image
          cache: maven

      - name: Verify GraalVM
        run: |
          java -version
          native-image --version
          mvn -version

      - name: Build Quarkus Native Image (Linux)
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}
        run: |
          mvn clean package -Pnative -DskipTests

      - name: Upload Native Binary runner
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-native-linux
          path: target/*-runner
